export const FETCH_IN_CINEMA = 'FETCH_IN_CINEMA';
export const FETCH_MOVIE_BY_ID = 'FETCH_MOVIE_BY_ID';
export const FETCH_MOVIE_CREDIT = 'FETCH_MOVIE_CREDIT';
export const FETCH_SIMILAR = 'FETCH_SIMILAR';